# TauTau Channel Models
tt:
  model_name: 'model_tt'
  model_path: "../../Training/python/XGB_Models/prod_oct/tt/"
  model_type: "BDT"
  # model_cut: "VTight"
# MuTau Channel Models
mt:
  model_name: 'model_mt'
  model_path: "../../Training/python/XGB_Models/prod_oct/mt"
  model_type: "BDT"
# ETau Channel Models
et:
  model_name: 'model_et'
  model_path: "../../Training/python/XGB_Models/prod_oct/et"
  model_type: "BDT"



# tt_medium:
#   model_name: 'model_opt_medium'
#   model_path: "../../Training/python/XGB_Models/EarlyRun3/tt"
#   model_type: "BDT"
#   model_cut: "Medium"
# tt_tight:
#   model_name: 'model_opt_tight'
#   model_path: "../../Training/python/XGB_Models/EarlyRun3/tt"
#   model_type: "BDT"
#   model_cut: "Tight"